-- Seed official templates (idempotent)
INSERT INTO funnel_templates (tenant_id, name, description, category, funnel_json, is_public, price_cents, downloads_count)
SELECT null, 'Funil de Captação Simples', 'Captura leads com isca digital e segmenta engajados de frios.', 'captacao',
'{"blocks":[{"id":"b1","block_type":"entry","label":"Entrada","config":{"entry_type":"link_utm"},"position_x":100,"position_y":50},{"id":"b2","block_type":"message","label":"Boas-vindas","config":{"channel":"whatsapp","content":"Olá! Seja bem-vindo(a)!"},"position_x":100,"position_y":150},{"id":"b3","block_type":"delay","label":"Delay 1h","config":{"amount":1,"unit":"hours"},"position_x":100,"position_y":250},{"id":"b4","block_type":"message","label":"Entrega da Isca","config":{"channel":"whatsapp","content":"Aqui está seu material exclusivo!"},"position_x":100,"position_y":350},{"id":"b5","block_type":"condition","label":"Abriu a mensagem?","config":{"condition_type":"opened"},"position_x":100,"position_y":450},{"id":"b6","block_type":"tag","label":"Tag Engajado","config":{"action":"add","tag":"engajado"},"position_x":0,"position_y":580},{"id":"b7","block_type":"tag","label":"Tag Frio","config":{"action":"add","tag":"frio"},"position_x":200,"position_y":580}],"edges":[{"id":"e1","source_block_id":"b1","target_block_id":"b2","condition":"default"},{"id":"e2","source_block_id":"b2","target_block_id":"b3","condition":"default"},{"id":"e3","source_block_id":"b3","target_block_id":"b4","condition":"default"},{"id":"e4","source_block_id":"b4","target_block_id":"b5","condition":"default"},{"id":"e5","source_block_id":"b5","target_block_id":"b6","condition":"opened"},{"id":"e6","source_block_id":"b5","target_block_id":"b7","condition":"not_opened"}]}'::jsonb,
true, 0, 47
WHERE NOT EXISTS (SELECT 1 FROM funnel_templates WHERE name = 'Funil de Captação Simples' AND tenant_id IS NULL);

INSERT INTO funnel_templates (tenant_id, name, description, category, funnel_json, is_public, price_cents, downloads_count)
SELECT null, 'Funil de Carrinho Abandonado', 'Recupera vendas de carrinhos abandonados com sequência de urgência.', 'cart_abandoned',
'{"blocks":[{"id":"c1","block_type":"cart_abandoned","label":"Carr. Abandonado","config":{"platform":"all"},"position_x":100,"position_y":50},{"id":"c2","block_type":"delay","label":"Delay 30min","config":{"amount":30,"unit":"minutes"},"position_x":100,"position_y":150},{"id":"c3","block_type":"message","label":"Mensagem Recuperação","config":{"channel":"whatsapp","content":"Oi! Vi que você deixou algo no carrinho."},"position_x":100,"position_y":250},{"id":"c4","block_type":"delay","label":"Delay 24h","config":{"amount":24,"unit":"hours"},"position_x":100,"position_y":350},{"id":"c5","block_type":"message","label":"Mensagem Urgência","config":{"channel":"whatsapp","content":"Últimas horas! Seu carrinho expira em breve."},"position_x":100,"position_y":450},{"id":"c6","block_type":"sale","label":"Venda","config":{"payment_link":""},"position_x":100,"position_y":550}],"edges":[{"id":"e1","source_block_id":"c1","target_block_id":"c2","condition":"default"},{"id":"e2","source_block_id":"c2","target_block_id":"c3","condition":"default"},{"id":"e3","source_block_id":"c3","target_block_id":"c4","condition":"default"},{"id":"e4","source_block_id":"c4","target_block_id":"c5","condition":"default"},{"id":"e5","source_block_id":"c5","target_block_id":"c6","condition":"default"}]}'::jsonb,
true, 0, 31
WHERE NOT EXISTS (SELECT 1 FROM funnel_templates WHERE name = 'Funil de Carrinho Abandonado' AND tenant_id IS NULL);

INSERT INTO funnel_templates (tenant_id, name, description, category, funnel_json, is_public, price_cents, downloads_count)
SELECT null, 'Funil de Lançamento 7 Dias', 'Sequência de aquecimento de 7 dias com abertura de carrinho no final.', 'lancamento',
'{"blocks":[{"id":"l1","block_type":"entry","label":"Entrada","config":{"entry_type":"link_utm"},"position_x":100,"position_y":50},{"id":"l2","block_type":"message","label":"Dia 1 — Conteúdo","config":{"channel":"whatsapp","content":"Bem-vindo(a) ao desafio!"},"position_x":100,"position_y":150},{"id":"l3","block_type":"delay","label":"Delay 24h","config":{"amount":24,"unit":"hours"},"position_x":100,"position_y":250},{"id":"l4","block_type":"message","label":"Dia 2 — Conteúdo","config":{"channel":"whatsapp","content":"Dia 2! Hoje você vai aprender..."},"position_x":100,"position_y":350},{"id":"l5","block_type":"delay","label":"Delay 24h","config":{"amount":24,"unit":"hours"},"position_x":100,"position_y":450},{"id":"l6","block_type":"message","label":"Dia 3 — Conteúdo","config":{"channel":"whatsapp","content":"Dia 3 — O segredo que ninguém te conta..."},"position_x":100,"position_y":550},{"id":"l7","block_type":"condition","label":"Está engajado?","config":{"condition_type":"opened"},"position_x":100,"position_y":650},{"id":"l8","block_type":"message","label":"Abertura Carrinho","config":{"channel":"whatsapp","content":"O carrinho está ABERTO!"},"position_x":100,"position_y":780},{"id":"l9","block_type":"sale","label":"Venda","config":{"payment_link":""},"position_x":100,"position_y":880}],"edges":[{"id":"e1","source_block_id":"l1","target_block_id":"l2","condition":"default"},{"id":"e2","source_block_id":"l2","target_block_id":"l3","condition":"default"},{"id":"e3","source_block_id":"l3","target_block_id":"l4","condition":"default"},{"id":"e4","source_block_id":"l4","target_block_id":"l5","condition":"default"},{"id":"e5","source_block_id":"l5","target_block_id":"l6","condition":"default"},{"id":"e6","source_block_id":"l6","target_block_id":"l7","condition":"default"},{"id":"e7","source_block_id":"l7","target_block_id":"l8","condition":"opened"},{"id":"e8","source_block_id":"l7","target_block_id":"l8","condition":"not_opened"},{"id":"e9","source_block_id":"l8","target_block_id":"l9","condition":"default"}]}'::jsonb,
true, 0, 19
WHERE NOT EXISTS (SELECT 1 FROM funnel_templates WHERE name = 'Funil de Lançamento 7 Dias' AND tenant_id IS NULL);
